package edu.colostate.cs.cs414.f18.the_other_alex.model;

import java.util.ArrayList;

public class User {
  private String username;
  private String email;
  private String password;
  private ArrayList<Invite> pendingInvites;
  private ArrayList<Invite> pendingReceivedInvites;
  private UserHistory userHistory;
  private ArrayList<String> games;

  public User(String username, String email, String password) {
    if (isValidUsername(username)) {
      this.username = username;
    }
    setPassword(password);
    setEmail(email);
  }

  /**
   * The receiving user is already listed in the invite.
   * @param invite
   */
  public void receiveInvite(Invite invite) {
    pendingReceivedInvites.add(invite);
  }

  public Invite sendInvite(Invite invite, String username) {
      invite.send(username); // does nothing if already invited
      return invite;
  }

  private Invite getSendInvite(String inviteId) {
    for (Invite invite : pendingInvites) {
      if (invite.getId().equals(inviteId)) {
        return invite;
      }
    }
    return null;
  }

  /**
   * The model will generate an inviteId (or retrieve it from the invite it has). It calls the user's sendInvite
   * method to have the user add the invite to its existing invite or create a new one if it doesn't already have that
   * invite.
   *
   * @param inviteId The inviteId generated by the model
   * @param username The username of the person being invited.
   * @return
   */
  public Invite sendInvite(String inviteId, String username) {
    Invite invite = getSendInvite(inviteId);
    if (invite == null) {
      invite = new Invite(this, inviteId);
      pendingInvites.add(invite);
    }
    return sendInvite(invite, username);
  }

  private boolean isNonEmpty(String string) {
    return !(password == null || password.length() == 0);
  }

  /**
   * This validates the format not uniqueness. Uniqueness should be checked wherever the user object is created. This
   * is because we want to be able to create user objects even though a user with that username already exists.
   * @param username Username of users.
   * @return True if username is valid
   */
  private boolean isValidUsername(String username) {
    return isNonEmpty(username);
  }

  private boolean isValidPassword(String password) {
    return isNonEmpty(password);
  }

  private boolean isValidEmail(String email) {
    return isNonEmpty(email);
  }

  public void setPassword(String newPassword) {
    if (isValidPassword(newPassword)) {
      password = newPassword;
    }
  }

  public void setEmail(String newEmail) {
    if (isValidEmail(newEmail)) {
      email = newEmail;
    }
  }

  /**
   * called by game object when updated
   */
  public void update() {
    // TODO
  }

  public UserHistory getUserHistory() {
    return userHistory;
  }

  public String getUsername() {
    return username;
  }

  public String getEmail() {
    return email;
  }

  public ArrayList<Invite> getInvites() {
    return pendingInvites;
  }

  public ArrayList<String> getGames() {
    return games;
  }
}
